### ISSUE TITLE
api error

### ISSUE THREAD

**Issue by 0x13ens** [smokelaboratory/flutter_api_structure#1]
I/flutter (32724): API call : Instance of 'RequestOptions'

**Comment by smokelaboratory** [comment]
Hi @0x13ens. This is just a log which gets printed with every request. 
![Screenshot 2019-12-16 at 1 37 39 PM](https://user-images.githubusercontent.com/53153241/70889830-7e101880-2009-11ea-8237-66d39bc4ec25.png)

Please add a print statement in error/success toast methods in base screen to get the output printed. Also, you can pull the latest code with required changes.
